// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AccountService.proto

#include "AccountService.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr ResponseAccountData::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : account_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        account_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        account_password_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        account_password_to_verify_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ResponseAccountData::ResponseAccountData(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ResponseAccountDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ResponseAccountDataDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ResponseAccountDataDefaultTypeInternal() {}
  union {
    ResponseAccountData _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ResponseAccountDataDefaultTypeInternal _ResponseAccountData_default_instance_;

inline constexpr RequestCharacterList::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : account_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR RequestCharacterList::RequestCharacterList(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct RequestCharacterListDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RequestCharacterListDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RequestCharacterListDefaultTypeInternal() {}
  union {
    RequestCharacterList _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RequestCharacterListDefaultTypeInternal _RequestCharacterList_default_instance_;

inline constexpr RequestAccountData::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : account_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        account_password_to_verify_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR RequestAccountData::RequestAccountData(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct RequestAccountDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RequestAccountDataDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RequestAccountDataDefaultTypeInternal() {}
  union {
    RequestAccountData _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RequestAccountDataDefaultTypeInternal _RequestAccountData_default_instance_;

inline constexpr CharacterBaseData::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : character_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        slot_number_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CharacterBaseData::CharacterBaseData(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct CharacterBaseDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CharacterBaseDataDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CharacterBaseDataDefaultTypeInternal() {}
  union {
    CharacterBaseData _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CharacterBaseDataDefaultTypeInternal _CharacterBaseData_default_instance_;

inline constexpr ResponseCharacterList::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : characters_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ResponseCharacterList::ResponseCharacterList(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ResponseCharacterListDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ResponseCharacterListDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ResponseCharacterListDefaultTypeInternal() {}
  union {
    ResponseCharacterList _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ResponseCharacterListDefaultTypeInternal _ResponseCharacterList_default_instance_;

inline constexpr AccountServiceRequestWrapper::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : request_{},
        _cached_size_{0},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR AccountServiceRequestWrapper::AccountServiceRequestWrapper(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct AccountServiceRequestWrapperDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AccountServiceRequestWrapperDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AccountServiceRequestWrapperDefaultTypeInternal() {}
  union {
    AccountServiceRequestWrapper _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AccountServiceRequestWrapperDefaultTypeInternal _AccountServiceRequestWrapper_default_instance_;

inline constexpr AccountServiceResponseWrapper::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : response_{},
        _cached_size_{0},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR AccountServiceResponseWrapper::AccountServiceResponseWrapper(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct AccountServiceResponseWrapperDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AccountServiceResponseWrapperDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AccountServiceResponseWrapperDefaultTypeInternal() {}
  union {
    AccountServiceResponseWrapper _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AccountServiceResponseWrapperDefaultTypeInternal _AccountServiceResponseWrapper_default_instance_;
static ::_pb::Metadata file_level_metadata_AccountService_2eproto[7];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_AccountService_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_AccountService_2eproto = nullptr;
const ::uint32_t TableStruct_AccountService_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::AccountServiceRequestWrapper, _internal_metadata_),
    ~0u,  // no _extensions_
    PROTOBUF_FIELD_OFFSET(::AccountServiceRequestWrapper, _impl_._oneof_case_[0]),
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    ::_pbi::kInvalidFieldOffsetTag,
    ::_pbi::kInvalidFieldOffsetTag,
    PROTOBUF_FIELD_OFFSET(::AccountServiceRequestWrapper, _impl_.request_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::AccountServiceResponseWrapper, _internal_metadata_),
    ~0u,  // no _extensions_
    PROTOBUF_FIELD_OFFSET(::AccountServiceResponseWrapper, _impl_._oneof_case_[0]),
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    ::_pbi::kInvalidFieldOffsetTag,
    ::_pbi::kInvalidFieldOffsetTag,
    PROTOBUF_FIELD_OFFSET(::AccountServiceResponseWrapper, _impl_.response_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::RequestAccountData, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::RequestAccountData, _impl_.account_name_),
    PROTOBUF_FIELD_OFFSET(::RequestAccountData, _impl_.account_password_to_verify_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::ResponseAccountData, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::ResponseAccountData, _impl_.account_id_),
    PROTOBUF_FIELD_OFFSET(::ResponseAccountData, _impl_.account_name_),
    PROTOBUF_FIELD_OFFSET(::ResponseAccountData, _impl_.account_password_),
    PROTOBUF_FIELD_OFFSET(::ResponseAccountData, _impl_.account_password_to_verify_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::RequestCharacterList, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::RequestCharacterList, _impl_.account_name_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::CharacterBaseData, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::CharacterBaseData, _impl_.slot_number_),
    PROTOBUF_FIELD_OFFSET(::CharacterBaseData, _impl_.character_name_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::ResponseCharacterList, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::ResponseCharacterList, _impl_.characters_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::AccountServiceRequestWrapper)},
        {11, -1, -1, sizeof(::AccountServiceResponseWrapper)},
        {22, -1, -1, sizeof(::RequestAccountData)},
        {32, -1, -1, sizeof(::ResponseAccountData)},
        {44, -1, -1, sizeof(::RequestCharacterList)},
        {53, -1, -1, sizeof(::CharacterBaseData)},
        {63, -1, -1, sizeof(::ResponseCharacterList)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::_AccountServiceRequestWrapper_default_instance_._instance,
    &::_AccountServiceResponseWrapper_default_instance_._instance,
    &::_RequestAccountData_default_instance_._instance,
    &::_ResponseAccountData_default_instance_._instance,
    &::_RequestCharacterList_default_instance_._instance,
    &::_CharacterBaseData_default_instance_._instance,
    &::_ResponseCharacterList_default_instance_._instance,
};
const char descriptor_table_protodef_AccountService_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\024AccountService.proto\"\227\001\n\034AccountServic"
    "eRequestWrapper\0223\n\024request_account_data\030"
    "\002 \001(\0132\023.RequestAccountDataH\000\0227\n\026request_"
    "character_list\030\003 \001(\0132\025.RequestCharacterL"
    "istH\000B\t\n\007request\"\235\001\n\035AccountServiceRespo"
    "nseWrapper\0225\n\025response_account_data\030\002 \001("
    "\0132\024.ResponseAccountDataH\000\0229\n\027response_ch"
    "aracter_list\030\003 \001(\0132\026.ResponseCharacterLi"
    "stH\000B\n\n\010response\"N\n\022RequestAccountData\022\024"
    "\n\014account_name\030\001 \001(\t\022\"\n\032account_password"
    "_to_verify\030\002 \001(\t\"}\n\023ResponseAccountData\022"
    "\022\n\naccount_id\030\001 \001(\t\022\024\n\014account_name\030\002 \001("
    "\t\022\030\n\020account_password\030\003 \001(\t\022\"\n\032account_p"
    "assword_to_verify\030\004 \001(\t\",\n\024RequestCharac"
    "terList\022\024\n\014account_name\030\001 \001(\t\"@\n\021Charact"
    "erBaseData\022\023\n\013slot_number\030\001 \001(\r\022\026\n\016chara"
    "cter_name\030\002 \001(\t\"\?\n\025ResponseCharacterList"
    "\022&\n\ncharacters\030\001 \003(\0132\022.CharacterBaseData"
    "b\006proto3"
};
static ::absl::once_flag descriptor_table_AccountService_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_AccountService_2eproto = {
    false,
    false,
    728,
    descriptor_table_protodef_AccountService_2eproto,
    "AccountService.proto",
    &descriptor_table_AccountService_2eproto_once,
    nullptr,
    0,
    7,
    schemas,
    file_default_instances,
    TableStruct_AccountService_2eproto::offsets,
    file_level_metadata_AccountService_2eproto,
    file_level_enum_descriptors_AccountService_2eproto,
    file_level_service_descriptors_AccountService_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_AccountService_2eproto_getter() {
  return &descriptor_table_AccountService_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_AccountService_2eproto(&descriptor_table_AccountService_2eproto);
// ===================================================================

class AccountServiceRequestWrapper::_Internal {
 public:
  static constexpr ::int32_t kOneofCaseOffset =
    PROTOBUF_FIELD_OFFSET(::AccountServiceRequestWrapper, _impl_._oneof_case_);
  static const ::RequestAccountData& request_account_data(const AccountServiceRequestWrapper* msg);
  static const ::RequestCharacterList& request_character_list(const AccountServiceRequestWrapper* msg);
};

const ::RequestAccountData& AccountServiceRequestWrapper::_Internal::request_account_data(const AccountServiceRequestWrapper* msg) {
  return *msg->_impl_.request_.request_account_data_;
}
const ::RequestCharacterList& AccountServiceRequestWrapper::_Internal::request_character_list(const AccountServiceRequestWrapper* msg) {
  return *msg->_impl_.request_.request_character_list_;
}
void AccountServiceRequestWrapper::set_allocated_request_account_data(::RequestAccountData* request_account_data) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_request();
  if (request_account_data) {
    ::google::protobuf::Arena* submessage_arena = request_account_data->GetArena();
    if (message_arena != submessage_arena) {
      request_account_data = ::google::protobuf::internal::GetOwnedMessage(message_arena, request_account_data, submessage_arena);
    }
    set_has_request_account_data();
    _impl_.request_.request_account_data_ = request_account_data;
  }
  // @@protoc_insertion_point(field_set_allocated:AccountServiceRequestWrapper.request_account_data)
}
void AccountServiceRequestWrapper::set_allocated_request_character_list(::RequestCharacterList* request_character_list) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_request();
  if (request_character_list) {
    ::google::protobuf::Arena* submessage_arena = request_character_list->GetArena();
    if (message_arena != submessage_arena) {
      request_character_list = ::google::protobuf::internal::GetOwnedMessage(message_arena, request_character_list, submessage_arena);
    }
    set_has_request_character_list();
    _impl_.request_.request_character_list_ = request_character_list;
  }
  // @@protoc_insertion_point(field_set_allocated:AccountServiceRequestWrapper.request_character_list)
}
AccountServiceRequestWrapper::AccountServiceRequestWrapper(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:AccountServiceRequestWrapper)
}
inline PROTOBUF_NDEBUG_INLINE AccountServiceRequestWrapper::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : request_{},
        _cached_size_{0},
        _oneof_case_{from._oneof_case_[0]} {}

AccountServiceRequestWrapper::AccountServiceRequestWrapper(
    ::google::protobuf::Arena* arena,
    const AccountServiceRequestWrapper& from)
    : ::google::protobuf::Message(arena) {
  AccountServiceRequestWrapper* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  switch (request_case()) {
    case REQUEST_NOT_SET:
      break;
      case kRequestAccountData:
        _impl_.request_.request_account_data_ = CreateMaybeMessage<::RequestAccountData>(arena, *from._impl_.request_.request_account_data_);
        break;
      case kRequestCharacterList:
        _impl_.request_.request_character_list_ = CreateMaybeMessage<::RequestCharacterList>(arena, *from._impl_.request_.request_character_list_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:AccountServiceRequestWrapper)
}
inline PROTOBUF_NDEBUG_INLINE AccountServiceRequestWrapper::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : request_{},
        _cached_size_{0},
        _oneof_case_{} {}

inline void AccountServiceRequestWrapper::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
AccountServiceRequestWrapper::~AccountServiceRequestWrapper() {
  // @@protoc_insertion_point(destructor:AccountServiceRequestWrapper)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void AccountServiceRequestWrapper::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  if (has_request()) {
    clear_request();
  }
  _impl_.~Impl_();
}

void AccountServiceRequestWrapper::clear_request() {
// @@protoc_insertion_point(one_of_clear_start:AccountServiceRequestWrapper)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  switch (request_case()) {
    case kRequestAccountData: {
      if (GetArena() == nullptr) {
        delete _impl_.request_.request_account_data_;
      }
      break;
    }
    case kRequestCharacterList: {
      if (GetArena() == nullptr) {
        delete _impl_.request_.request_character_list_;
      }
      break;
    }
    case REQUEST_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = REQUEST_NOT_SET;
}


PROTOBUF_NOINLINE void AccountServiceRequestWrapper::Clear() {
// @@protoc_insertion_point(message_clear_start:AccountServiceRequestWrapper)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_request();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* AccountServiceRequestWrapper::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 2, 2, 0, 2> AccountServiceRequestWrapper::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967289,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_AccountServiceRequestWrapper_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .RequestAccountData request_account_data = 2;
    {PROTOBUF_FIELD_OFFSET(AccountServiceRequestWrapper, _impl_.request_.request_account_data_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .RequestCharacterList request_character_list = 3;
    {PROTOBUF_FIELD_OFFSET(AccountServiceRequestWrapper, _impl_.request_.request_character_list_), _Internal::kOneofCaseOffset + 0, 1,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::RequestAccountData>()},
    {::_pbi::TcParser::GetTable<::RequestCharacterList>()},
  }}, {{
  }},
};

::uint8_t* AccountServiceRequestWrapper::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:AccountServiceRequestWrapper)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  switch (request_case()) {
    case kRequestAccountData: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          2, _Internal::request_account_data(this),
          _Internal::request_account_data(this).GetCachedSize(), target, stream);
      break;
    }
    case kRequestCharacterList: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          3, _Internal::request_character_list(this),
          _Internal::request_character_list(this).GetCachedSize(), target, stream);
      break;
    }
    default:
      break;
  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:AccountServiceRequestWrapper)
  return target;
}

::size_t AccountServiceRequestWrapper::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:AccountServiceRequestWrapper)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  switch (request_case()) {
    // .RequestAccountData request_account_data = 2;
    case kRequestAccountData: {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.request_.request_account_data_);
      break;
    }
    // .RequestCharacterList request_character_list = 3;
    case kRequestCharacterList: {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.request_.request_character_list_);
      break;
    }
    case REQUEST_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData AccountServiceRequestWrapper::_class_data_ = {
    AccountServiceRequestWrapper::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* AccountServiceRequestWrapper::GetClassData() const {
  return &_class_data_;
}

void AccountServiceRequestWrapper::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<AccountServiceRequestWrapper*>(&to_msg);
  auto& from = static_cast<const AccountServiceRequestWrapper&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:AccountServiceRequestWrapper)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  switch (from.request_case()) {
    case kRequestAccountData: {
      _this->_internal_mutable_request_account_data()->::RequestAccountData::MergeFrom(
          from._internal_request_account_data());
      break;
    }
    case kRequestCharacterList: {
      _this->_internal_mutable_request_character_list()->::RequestCharacterList::MergeFrom(
          from._internal_request_character_list());
      break;
    }
    case REQUEST_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void AccountServiceRequestWrapper::CopyFrom(const AccountServiceRequestWrapper& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:AccountServiceRequestWrapper)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool AccountServiceRequestWrapper::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* AccountServiceRequestWrapper::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void AccountServiceRequestWrapper::InternalSwap(AccountServiceRequestWrapper* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.request_, other->_impl_.request_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata AccountServiceRequestWrapper::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_AccountService_2eproto_getter, &descriptor_table_AccountService_2eproto_once,
      file_level_metadata_AccountService_2eproto[0]);
}
// ===================================================================

class AccountServiceResponseWrapper::_Internal {
 public:
  static constexpr ::int32_t kOneofCaseOffset =
    PROTOBUF_FIELD_OFFSET(::AccountServiceResponseWrapper, _impl_._oneof_case_);
  static const ::ResponseAccountData& response_account_data(const AccountServiceResponseWrapper* msg);
  static const ::ResponseCharacterList& response_character_list(const AccountServiceResponseWrapper* msg);
};

const ::ResponseAccountData& AccountServiceResponseWrapper::_Internal::response_account_data(const AccountServiceResponseWrapper* msg) {
  return *msg->_impl_.response_.response_account_data_;
}
const ::ResponseCharacterList& AccountServiceResponseWrapper::_Internal::response_character_list(const AccountServiceResponseWrapper* msg) {
  return *msg->_impl_.response_.response_character_list_;
}
void AccountServiceResponseWrapper::set_allocated_response_account_data(::ResponseAccountData* response_account_data) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_response();
  if (response_account_data) {
    ::google::protobuf::Arena* submessage_arena = response_account_data->GetArena();
    if (message_arena != submessage_arena) {
      response_account_data = ::google::protobuf::internal::GetOwnedMessage(message_arena, response_account_data, submessage_arena);
    }
    set_has_response_account_data();
    _impl_.response_.response_account_data_ = response_account_data;
  }
  // @@protoc_insertion_point(field_set_allocated:AccountServiceResponseWrapper.response_account_data)
}
void AccountServiceResponseWrapper::set_allocated_response_character_list(::ResponseCharacterList* response_character_list) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_response();
  if (response_character_list) {
    ::google::protobuf::Arena* submessage_arena = response_character_list->GetArena();
    if (message_arena != submessage_arena) {
      response_character_list = ::google::protobuf::internal::GetOwnedMessage(message_arena, response_character_list, submessage_arena);
    }
    set_has_response_character_list();
    _impl_.response_.response_character_list_ = response_character_list;
  }
  // @@protoc_insertion_point(field_set_allocated:AccountServiceResponseWrapper.response_character_list)
}
AccountServiceResponseWrapper::AccountServiceResponseWrapper(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:AccountServiceResponseWrapper)
}
inline PROTOBUF_NDEBUG_INLINE AccountServiceResponseWrapper::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : response_{},
        _cached_size_{0},
        _oneof_case_{from._oneof_case_[0]} {}

AccountServiceResponseWrapper::AccountServiceResponseWrapper(
    ::google::protobuf::Arena* arena,
    const AccountServiceResponseWrapper& from)
    : ::google::protobuf::Message(arena) {
  AccountServiceResponseWrapper* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  switch (response_case()) {
    case RESPONSE_NOT_SET:
      break;
      case kResponseAccountData:
        _impl_.response_.response_account_data_ = CreateMaybeMessage<::ResponseAccountData>(arena, *from._impl_.response_.response_account_data_);
        break;
      case kResponseCharacterList:
        _impl_.response_.response_character_list_ = CreateMaybeMessage<::ResponseCharacterList>(arena, *from._impl_.response_.response_character_list_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:AccountServiceResponseWrapper)
}
inline PROTOBUF_NDEBUG_INLINE AccountServiceResponseWrapper::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : response_{},
        _cached_size_{0},
        _oneof_case_{} {}

inline void AccountServiceResponseWrapper::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
AccountServiceResponseWrapper::~AccountServiceResponseWrapper() {
  // @@protoc_insertion_point(destructor:AccountServiceResponseWrapper)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void AccountServiceResponseWrapper::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  if (has_response()) {
    clear_response();
  }
  _impl_.~Impl_();
}

void AccountServiceResponseWrapper::clear_response() {
// @@protoc_insertion_point(one_of_clear_start:AccountServiceResponseWrapper)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  switch (response_case()) {
    case kResponseAccountData: {
      if (GetArena() == nullptr) {
        delete _impl_.response_.response_account_data_;
      }
      break;
    }
    case kResponseCharacterList: {
      if (GetArena() == nullptr) {
        delete _impl_.response_.response_character_list_;
      }
      break;
    }
    case RESPONSE_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = RESPONSE_NOT_SET;
}


PROTOBUF_NOINLINE void AccountServiceResponseWrapper::Clear() {
// @@protoc_insertion_point(message_clear_start:AccountServiceResponseWrapper)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_response();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* AccountServiceResponseWrapper::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 2, 2, 0, 2> AccountServiceResponseWrapper::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967289,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_AccountServiceResponseWrapper_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .ResponseAccountData response_account_data = 2;
    {PROTOBUF_FIELD_OFFSET(AccountServiceResponseWrapper, _impl_.response_.response_account_data_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .ResponseCharacterList response_character_list = 3;
    {PROTOBUF_FIELD_OFFSET(AccountServiceResponseWrapper, _impl_.response_.response_character_list_), _Internal::kOneofCaseOffset + 0, 1,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::ResponseAccountData>()},
    {::_pbi::TcParser::GetTable<::ResponseCharacterList>()},
  }}, {{
  }},
};

::uint8_t* AccountServiceResponseWrapper::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:AccountServiceResponseWrapper)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  switch (response_case()) {
    case kResponseAccountData: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          2, _Internal::response_account_data(this),
          _Internal::response_account_data(this).GetCachedSize(), target, stream);
      break;
    }
    case kResponseCharacterList: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          3, _Internal::response_character_list(this),
          _Internal::response_character_list(this).GetCachedSize(), target, stream);
      break;
    }
    default:
      break;
  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:AccountServiceResponseWrapper)
  return target;
}

::size_t AccountServiceResponseWrapper::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:AccountServiceResponseWrapper)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  switch (response_case()) {
    // .ResponseAccountData response_account_data = 2;
    case kResponseAccountData: {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.response_.response_account_data_);
      break;
    }
    // .ResponseCharacterList response_character_list = 3;
    case kResponseCharacterList: {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.response_.response_character_list_);
      break;
    }
    case RESPONSE_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData AccountServiceResponseWrapper::_class_data_ = {
    AccountServiceResponseWrapper::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* AccountServiceResponseWrapper::GetClassData() const {
  return &_class_data_;
}

void AccountServiceResponseWrapper::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<AccountServiceResponseWrapper*>(&to_msg);
  auto& from = static_cast<const AccountServiceResponseWrapper&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:AccountServiceResponseWrapper)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  switch (from.response_case()) {
    case kResponseAccountData: {
      _this->_internal_mutable_response_account_data()->::ResponseAccountData::MergeFrom(
          from._internal_response_account_data());
      break;
    }
    case kResponseCharacterList: {
      _this->_internal_mutable_response_character_list()->::ResponseCharacterList::MergeFrom(
          from._internal_response_character_list());
      break;
    }
    case RESPONSE_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void AccountServiceResponseWrapper::CopyFrom(const AccountServiceResponseWrapper& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:AccountServiceResponseWrapper)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool AccountServiceResponseWrapper::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* AccountServiceResponseWrapper::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void AccountServiceResponseWrapper::InternalSwap(AccountServiceResponseWrapper* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.response_, other->_impl_.response_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata AccountServiceResponseWrapper::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_AccountService_2eproto_getter, &descriptor_table_AccountService_2eproto_once,
      file_level_metadata_AccountService_2eproto[1]);
}
// ===================================================================

class RequestAccountData::_Internal {
 public:
};

RequestAccountData::RequestAccountData(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:RequestAccountData)
}
inline PROTOBUF_NDEBUG_INLINE RequestAccountData::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : account_name_(arena, from.account_name_),
        account_password_to_verify_(arena, from.account_password_to_verify_),
        _cached_size_{0} {}

RequestAccountData::RequestAccountData(
    ::google::protobuf::Arena* arena,
    const RequestAccountData& from)
    : ::google::protobuf::Message(arena) {
  RequestAccountData* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:RequestAccountData)
}
inline PROTOBUF_NDEBUG_INLINE RequestAccountData::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : account_name_(arena),
        account_password_to_verify_(arena),
        _cached_size_{0} {}

inline void RequestAccountData::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
RequestAccountData::~RequestAccountData() {
  // @@protoc_insertion_point(destructor:RequestAccountData)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void RequestAccountData::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.account_name_.Destroy();
  _impl_.account_password_to_verify_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void RequestAccountData::Clear() {
// @@protoc_insertion_point(message_clear_start:RequestAccountData)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.account_name_.ClearToEmpty();
  _impl_.account_password_to_verify_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* RequestAccountData::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 65, 2> RequestAccountData::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_RequestAccountData_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string account_password_to_verify = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(RequestAccountData, _impl_.account_password_to_verify_)}},
    // string account_name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(RequestAccountData, _impl_.account_name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string account_name = 1;
    {PROTOBUF_FIELD_OFFSET(RequestAccountData, _impl_.account_name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string account_password_to_verify = 2;
    {PROTOBUF_FIELD_OFFSET(RequestAccountData, _impl_.account_password_to_verify_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\22\14\32\0\0\0\0\0"
    "RequestAccountData"
    "account_name"
    "account_password_to_verify"
  }},
};

::uint8_t* RequestAccountData::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:RequestAccountData)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string account_name = 1;
  if (!this->_internal_account_name().empty()) {
    const std::string& _s = this->_internal_account_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "RequestAccountData.account_name");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string account_password_to_verify = 2;
  if (!this->_internal_account_password_to_verify().empty()) {
    const std::string& _s = this->_internal_account_password_to_verify();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "RequestAccountData.account_password_to_verify");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:RequestAccountData)
  return target;
}

::size_t RequestAccountData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:RequestAccountData)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string account_name = 1;
  if (!this->_internal_account_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_account_name());
  }

  // string account_password_to_verify = 2;
  if (!this->_internal_account_password_to_verify().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_account_password_to_verify());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData RequestAccountData::_class_data_ = {
    RequestAccountData::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* RequestAccountData::GetClassData() const {
  return &_class_data_;
}

void RequestAccountData::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<RequestAccountData*>(&to_msg);
  auto& from = static_cast<const RequestAccountData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:RequestAccountData)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_account_name().empty()) {
    _this->_internal_set_account_name(from._internal_account_name());
  }
  if (!from._internal_account_password_to_verify().empty()) {
    _this->_internal_set_account_password_to_verify(from._internal_account_password_to_verify());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RequestAccountData::CopyFrom(const RequestAccountData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:RequestAccountData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool RequestAccountData::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* RequestAccountData::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void RequestAccountData::InternalSwap(RequestAccountData* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.account_name_, &other->_impl_.account_name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.account_password_to_verify_, &other->_impl_.account_password_to_verify_, arena);
}

::google::protobuf::Metadata RequestAccountData::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_AccountService_2eproto_getter, &descriptor_table_AccountService_2eproto_once,
      file_level_metadata_AccountService_2eproto[2]);
}
// ===================================================================

class ResponseAccountData::_Internal {
 public:
};

ResponseAccountData::ResponseAccountData(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ResponseAccountData)
}
inline PROTOBUF_NDEBUG_INLINE ResponseAccountData::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : account_id_(arena, from.account_id_),
        account_name_(arena, from.account_name_),
        account_password_(arena, from.account_password_),
        account_password_to_verify_(arena, from.account_password_to_verify_),
        _cached_size_{0} {}

ResponseAccountData::ResponseAccountData(
    ::google::protobuf::Arena* arena,
    const ResponseAccountData& from)
    : ::google::protobuf::Message(arena) {
  ResponseAccountData* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:ResponseAccountData)
}
inline PROTOBUF_NDEBUG_INLINE ResponseAccountData::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : account_id_(arena),
        account_name_(arena),
        account_password_(arena),
        account_password_to_verify_(arena),
        _cached_size_{0} {}

inline void ResponseAccountData::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ResponseAccountData::~ResponseAccountData() {
  // @@protoc_insertion_point(destructor:ResponseAccountData)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ResponseAccountData::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.account_id_.Destroy();
  _impl_.account_name_.Destroy();
  _impl_.account_password_.Destroy();
  _impl_.account_password_to_verify_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void ResponseAccountData::Clear() {
// @@protoc_insertion_point(message_clear_start:ResponseAccountData)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.account_id_.ClearToEmpty();
  _impl_.account_name_.ClearToEmpty();
  _impl_.account_password_.ClearToEmpty();
  _impl_.account_password_to_verify_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ResponseAccountData::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 92, 2> ResponseAccountData::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_ResponseAccountData_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string account_password_to_verify = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(ResponseAccountData, _impl_.account_password_to_verify_)}},
    // string account_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ResponseAccountData, _impl_.account_id_)}},
    // string account_name = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(ResponseAccountData, _impl_.account_name_)}},
    // string account_password = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(ResponseAccountData, _impl_.account_password_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string account_id = 1;
    {PROTOBUF_FIELD_OFFSET(ResponseAccountData, _impl_.account_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string account_name = 2;
    {PROTOBUF_FIELD_OFFSET(ResponseAccountData, _impl_.account_name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string account_password = 3;
    {PROTOBUF_FIELD_OFFSET(ResponseAccountData, _impl_.account_password_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string account_password_to_verify = 4;
    {PROTOBUF_FIELD_OFFSET(ResponseAccountData, _impl_.account_password_to_verify_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\23\12\14\20\32\0\0\0"
    "ResponseAccountData"
    "account_id"
    "account_name"
    "account_password"
    "account_password_to_verify"
  }},
};

::uint8_t* ResponseAccountData::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ResponseAccountData)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string account_id = 1;
  if (!this->_internal_account_id().empty()) {
    const std::string& _s = this->_internal_account_id();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ResponseAccountData.account_id");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string account_name = 2;
  if (!this->_internal_account_name().empty()) {
    const std::string& _s = this->_internal_account_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ResponseAccountData.account_name");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // string account_password = 3;
  if (!this->_internal_account_password().empty()) {
    const std::string& _s = this->_internal_account_password();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ResponseAccountData.account_password");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // string account_password_to_verify = 4;
  if (!this->_internal_account_password_to_verify().empty()) {
    const std::string& _s = this->_internal_account_password_to_verify();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ResponseAccountData.account_password_to_verify");
    target = stream->WriteStringMaybeAliased(4, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ResponseAccountData)
  return target;
}

::size_t ResponseAccountData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ResponseAccountData)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string account_id = 1;
  if (!this->_internal_account_id().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_account_id());
  }

  // string account_name = 2;
  if (!this->_internal_account_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_account_name());
  }

  // string account_password = 3;
  if (!this->_internal_account_password().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_account_password());
  }

  // string account_password_to_verify = 4;
  if (!this->_internal_account_password_to_verify().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_account_password_to_verify());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData ResponseAccountData::_class_data_ = {
    ResponseAccountData::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* ResponseAccountData::GetClassData() const {
  return &_class_data_;
}

void ResponseAccountData::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<ResponseAccountData*>(&to_msg);
  auto& from = static_cast<const ResponseAccountData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ResponseAccountData)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_account_id().empty()) {
    _this->_internal_set_account_id(from._internal_account_id());
  }
  if (!from._internal_account_name().empty()) {
    _this->_internal_set_account_name(from._internal_account_name());
  }
  if (!from._internal_account_password().empty()) {
    _this->_internal_set_account_password(from._internal_account_password());
  }
  if (!from._internal_account_password_to_verify().empty()) {
    _this->_internal_set_account_password_to_verify(from._internal_account_password_to_verify());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ResponseAccountData::CopyFrom(const ResponseAccountData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ResponseAccountData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ResponseAccountData::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* ResponseAccountData::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void ResponseAccountData::InternalSwap(ResponseAccountData* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.account_id_, &other->_impl_.account_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.account_name_, &other->_impl_.account_name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.account_password_, &other->_impl_.account_password_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.account_password_to_verify_, &other->_impl_.account_password_to_verify_, arena);
}

::google::protobuf::Metadata ResponseAccountData::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_AccountService_2eproto_getter, &descriptor_table_AccountService_2eproto_once,
      file_level_metadata_AccountService_2eproto[3]);
}
// ===================================================================

class RequestCharacterList::_Internal {
 public:
};

RequestCharacterList::RequestCharacterList(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:RequestCharacterList)
}
inline PROTOBUF_NDEBUG_INLINE RequestCharacterList::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : account_name_(arena, from.account_name_),
        _cached_size_{0} {}

RequestCharacterList::RequestCharacterList(
    ::google::protobuf::Arena* arena,
    const RequestCharacterList& from)
    : ::google::protobuf::Message(arena) {
  RequestCharacterList* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:RequestCharacterList)
}
inline PROTOBUF_NDEBUG_INLINE RequestCharacterList::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : account_name_(arena),
        _cached_size_{0} {}

inline void RequestCharacterList::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
RequestCharacterList::~RequestCharacterList() {
  // @@protoc_insertion_point(destructor:RequestCharacterList)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void RequestCharacterList::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.account_name_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void RequestCharacterList::Clear() {
// @@protoc_insertion_point(message_clear_start:RequestCharacterList)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.account_name_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* RequestCharacterList::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 41, 2> RequestCharacterList::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_RequestCharacterList_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string account_name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(RequestCharacterList, _impl_.account_name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string account_name = 1;
    {PROTOBUF_FIELD_OFFSET(RequestCharacterList, _impl_.account_name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\24\14\0\0\0\0\0\0"
    "RequestCharacterList"
    "account_name"
  }},
};

::uint8_t* RequestCharacterList::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:RequestCharacterList)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string account_name = 1;
  if (!this->_internal_account_name().empty()) {
    const std::string& _s = this->_internal_account_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "RequestCharacterList.account_name");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:RequestCharacterList)
  return target;
}

::size_t RequestCharacterList::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:RequestCharacterList)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string account_name = 1;
  if (!this->_internal_account_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_account_name());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData RequestCharacterList::_class_data_ = {
    RequestCharacterList::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* RequestCharacterList::GetClassData() const {
  return &_class_data_;
}

void RequestCharacterList::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<RequestCharacterList*>(&to_msg);
  auto& from = static_cast<const RequestCharacterList&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:RequestCharacterList)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_account_name().empty()) {
    _this->_internal_set_account_name(from._internal_account_name());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RequestCharacterList::CopyFrom(const RequestCharacterList& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:RequestCharacterList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool RequestCharacterList::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* RequestCharacterList::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void RequestCharacterList::InternalSwap(RequestCharacterList* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.account_name_, &other->_impl_.account_name_, arena);
}

::google::protobuf::Metadata RequestCharacterList::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_AccountService_2eproto_getter, &descriptor_table_AccountService_2eproto_once,
      file_level_metadata_AccountService_2eproto[4]);
}
// ===================================================================

class CharacterBaseData::_Internal {
 public:
};

CharacterBaseData::CharacterBaseData(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:CharacterBaseData)
}
inline PROTOBUF_NDEBUG_INLINE CharacterBaseData::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : character_name_(arena, from.character_name_),
        _cached_size_{0} {}

CharacterBaseData::CharacterBaseData(
    ::google::protobuf::Arena* arena,
    const CharacterBaseData& from)
    : ::google::protobuf::Message(arena) {
  CharacterBaseData* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.slot_number_ = from._impl_.slot_number_;

  // @@protoc_insertion_point(copy_constructor:CharacterBaseData)
}
inline PROTOBUF_NDEBUG_INLINE CharacterBaseData::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : character_name_(arena),
        _cached_size_{0} {}

inline void CharacterBaseData::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.slot_number_ = {};
}
CharacterBaseData::~CharacterBaseData() {
  // @@protoc_insertion_point(destructor:CharacterBaseData)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void CharacterBaseData::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.character_name_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void CharacterBaseData::Clear() {
// @@protoc_insertion_point(message_clear_start:CharacterBaseData)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.character_name_.ClearToEmpty();
  _impl_.slot_number_ = 0u;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* CharacterBaseData::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 40, 2> CharacterBaseData::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_CharacterBaseData_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string character_name = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(CharacterBaseData, _impl_.character_name_)}},
    // uint32 slot_number = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CharacterBaseData, _impl_.slot_number_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(CharacterBaseData, _impl_.slot_number_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 slot_number = 1;
    {PROTOBUF_FIELD_OFFSET(CharacterBaseData, _impl_.slot_number_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // string character_name = 2;
    {PROTOBUF_FIELD_OFFSET(CharacterBaseData, _impl_.character_name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\21\0\16\0\0\0\0\0"
    "CharacterBaseData"
    "character_name"
  }},
};

::uint8_t* CharacterBaseData::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CharacterBaseData)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint32 slot_number = 1;
  if (this->_internal_slot_number() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this->_internal_slot_number(), target);
  }

  // string character_name = 2;
  if (!this->_internal_character_name().empty()) {
    const std::string& _s = this->_internal_character_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "CharacterBaseData.character_name");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CharacterBaseData)
  return target;
}

::size_t CharacterBaseData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CharacterBaseData)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string character_name = 2;
  if (!this->_internal_character_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_character_name());
  }

  // uint32 slot_number = 1;
  if (this->_internal_slot_number() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_slot_number());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData CharacterBaseData::_class_data_ = {
    CharacterBaseData::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* CharacterBaseData::GetClassData() const {
  return &_class_data_;
}

void CharacterBaseData::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<CharacterBaseData*>(&to_msg);
  auto& from = static_cast<const CharacterBaseData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:CharacterBaseData)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_character_name().empty()) {
    _this->_internal_set_character_name(from._internal_character_name());
  }
  if (from._internal_slot_number() != 0) {
    _this->_internal_set_slot_number(from._internal_slot_number());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CharacterBaseData::CopyFrom(const CharacterBaseData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CharacterBaseData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool CharacterBaseData::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* CharacterBaseData::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void CharacterBaseData::InternalSwap(CharacterBaseData* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.character_name_, &other->_impl_.character_name_, arena);
        swap(_impl_.slot_number_, other->_impl_.slot_number_);
}

::google::protobuf::Metadata CharacterBaseData::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_AccountService_2eproto_getter, &descriptor_table_AccountService_2eproto_once,
      file_level_metadata_AccountService_2eproto[5]);
}
// ===================================================================

class ResponseCharacterList::_Internal {
 public:
};

ResponseCharacterList::ResponseCharacterList(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ResponseCharacterList)
}
inline PROTOBUF_NDEBUG_INLINE ResponseCharacterList::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : characters_{visibility, arena, from.characters_},
        _cached_size_{0} {}

ResponseCharacterList::ResponseCharacterList(
    ::google::protobuf::Arena* arena,
    const ResponseCharacterList& from)
    : ::google::protobuf::Message(arena) {
  ResponseCharacterList* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:ResponseCharacterList)
}
inline PROTOBUF_NDEBUG_INLINE ResponseCharacterList::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : characters_{visibility, arena},
        _cached_size_{0} {}

inline void ResponseCharacterList::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ResponseCharacterList::~ResponseCharacterList() {
  // @@protoc_insertion_point(destructor:ResponseCharacterList)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ResponseCharacterList::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void ResponseCharacterList::Clear() {
// @@protoc_insertion_point(message_clear_start:ResponseCharacterList)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.characters_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ResponseCharacterList::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> ResponseCharacterList::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_ResponseCharacterList_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // repeated .CharacterBaseData characters = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ResponseCharacterList, _impl_.characters_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .CharacterBaseData characters = 1;
    {PROTOBUF_FIELD_OFFSET(ResponseCharacterList, _impl_.characters_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::CharacterBaseData>()},
  }}, {{
  }},
};

::uint8_t* ResponseCharacterList::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ResponseCharacterList)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated .CharacterBaseData characters = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_characters_size()); i < n; i++) {
    const auto& repfield = this->_internal_characters().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ResponseCharacterList)
  return target;
}

::size_t ResponseCharacterList::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ResponseCharacterList)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .CharacterBaseData characters = 1;
  total_size += 1UL * this->_internal_characters_size();
  for (const auto& msg : this->_internal_characters()) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData ResponseCharacterList::_class_data_ = {
    ResponseCharacterList::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* ResponseCharacterList::GetClassData() const {
  return &_class_data_;
}

void ResponseCharacterList::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<ResponseCharacterList*>(&to_msg);
  auto& from = static_cast<const ResponseCharacterList&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ResponseCharacterList)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_characters()->MergeFrom(
      from._internal_characters());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ResponseCharacterList::CopyFrom(const ResponseCharacterList& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ResponseCharacterList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ResponseCharacterList::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* ResponseCharacterList::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void ResponseCharacterList::InternalSwap(ResponseCharacterList* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.characters_.InternalSwap(&other->_impl_.characters_);
}

::google::protobuf::Metadata ResponseCharacterList::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_AccountService_2eproto_getter, &descriptor_table_AccountService_2eproto_once,
      file_level_metadata_AccountService_2eproto[6]);
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
