// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GameCharacterService.proto

#include "GameCharacterService.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr ResponsePlayerInitialData::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : player_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        position_x_{0},
        position_y_{0},
        position_z_{0},
        rotation_y_{0u},
        player_movementspeed_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ResponsePlayerInitialData::ResponsePlayerInitialData(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ResponsePlayerInitialDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ResponsePlayerInitialDataDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ResponsePlayerInitialDataDefaultTypeInternal() {}
  union {
    ResponsePlayerInitialData _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ResponsePlayerInitialDataDefaultTypeInternal _ResponsePlayerInitialData_default_instance_;

inline constexpr RequestPlayerInitialData::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : player_guid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR RequestPlayerInitialData::RequestPlayerInitialData(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct RequestPlayerInitialDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RequestPlayerInitialDataDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RequestPlayerInitialDataDefaultTypeInternal() {}
  union {
    RequestPlayerInitialData _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RequestPlayerInitialDataDefaultTypeInternal _RequestPlayerInitialData_default_instance_;

inline constexpr GameCharacterServiceResponseWrapper::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : response_type_{static_cast< ::GameCharacterServiceResponseWrapper_ResponseType >(0)},
        response_{},
        _cached_size_{0},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR GameCharacterServiceResponseWrapper::GameCharacterServiceResponseWrapper(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct GameCharacterServiceResponseWrapperDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GameCharacterServiceResponseWrapperDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GameCharacterServiceResponseWrapperDefaultTypeInternal() {}
  union {
    GameCharacterServiceResponseWrapper _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GameCharacterServiceResponseWrapperDefaultTypeInternal _GameCharacterServiceResponseWrapper_default_instance_;

inline constexpr GameCharacterServiceRequestWrapper::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : request_type_{static_cast< ::GameCharacterServiceRequestWrapper_RequestType >(0)},
        request_{},
        _cached_size_{0},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR GameCharacterServiceRequestWrapper::GameCharacterServiceRequestWrapper(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct GameCharacterServiceRequestWrapperDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GameCharacterServiceRequestWrapperDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GameCharacterServiceRequestWrapperDefaultTypeInternal() {}
  union {
    GameCharacterServiceRequestWrapper _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GameCharacterServiceRequestWrapperDefaultTypeInternal _GameCharacterServiceRequestWrapper_default_instance_;
static ::_pb::Metadata file_level_metadata_GameCharacterService_2eproto[4];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_GameCharacterService_2eproto[2];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_GameCharacterService_2eproto = nullptr;
const ::uint32_t TableStruct_GameCharacterService_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::GameCharacterServiceRequestWrapper, _internal_metadata_),
    ~0u,  // no _extensions_
    PROTOBUF_FIELD_OFFSET(::GameCharacterServiceRequestWrapper, _impl_._oneof_case_[0]),
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::GameCharacterServiceRequestWrapper, _impl_.request_type_),
    ::_pbi::kInvalidFieldOffsetTag,
    PROTOBUF_FIELD_OFFSET(::GameCharacterServiceRequestWrapper, _impl_.request_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::GameCharacterServiceResponseWrapper, _internal_metadata_),
    ~0u,  // no _extensions_
    PROTOBUF_FIELD_OFFSET(::GameCharacterServiceResponseWrapper, _impl_._oneof_case_[0]),
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::GameCharacterServiceResponseWrapper, _impl_.response_type_),
    ::_pbi::kInvalidFieldOffsetTag,
    PROTOBUF_FIELD_OFFSET(::GameCharacterServiceResponseWrapper, _impl_.response_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::RequestPlayerInitialData, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::RequestPlayerInitialData, _impl_.player_guid_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::ResponsePlayerInitialData, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::ResponsePlayerInitialData, _impl_.player_name_),
    PROTOBUF_FIELD_OFFSET(::ResponsePlayerInitialData, _impl_.position_x_),
    PROTOBUF_FIELD_OFFSET(::ResponsePlayerInitialData, _impl_.position_y_),
    PROTOBUF_FIELD_OFFSET(::ResponsePlayerInitialData, _impl_.position_z_),
    PROTOBUF_FIELD_OFFSET(::ResponsePlayerInitialData, _impl_.rotation_y_),
    PROTOBUF_FIELD_OFFSET(::ResponsePlayerInitialData, _impl_.player_movementspeed_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::GameCharacterServiceRequestWrapper)},
        {11, -1, -1, sizeof(::GameCharacterServiceResponseWrapper)},
        {22, -1, -1, sizeof(::RequestPlayerInitialData)},
        {31, -1, -1, sizeof(::ResponsePlayerInitialData)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::_GameCharacterServiceRequestWrapper_default_instance_._instance,
    &::_GameCharacterServiceResponseWrapper_default_instance_._instance,
    &::_RequestPlayerInitialData_default_instance_._instance,
    &::_ResponsePlayerInitialData_default_instance_._instance,
};
const char descriptor_table_protodef_GameCharacterService_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\032GameCharacterService.proto\"\345\001\n\"GameCha"
    "racterServiceRequestWrapper\022E\n\014request_t"
    "ype\030\001 \001(\0162/.GameCharacterServiceRequestW"
    "rapper.RequestType\022@\n\033request_player_ini"
    "tial_data\030\002 \001(\0132\031.RequestPlayerInitialDa"
    "taH\000\"+\n\013RequestType\022\034\n\030REQUESTPLAYERINIT"
    "IALDATA\020\000B\t\n\007request\"\356\001\n#GameCharacterSe"
    "rviceResponseWrapper\022H\n\rresponse_type\030\001 "
    "\001(\01621.GameCharacterServiceResponseWrappe"
    "r.ResponseType\022B\n\034response_player_initia"
    "l_data\030\002 \001(\0132\032.ResponsePlayerInitialData"
    "H\000\"-\n\014ResponseType\022\035\n\031RESPONSEPLAYERINIT"
    "IALDATA\020\000B\n\n\010response\"/\n\030RequestPlayerIn"
    "itialData\022\023\n\013player_guid\030\001 \001(\t\"\236\001\n\031Respo"
    "nsePlayerInitialData\022\023\n\013player_name\030\001 \001("
    "\t\022\022\n\nposition_x\030\002 \001(\002\022\022\n\nposition_y\030\003 \001("
    "\002\022\022\n\nposition_z\030\004 \001(\002\022\022\n\nrotation_y\030\005 \001("
    "\r\022\034\n\024player_movementspeed\030\006 \001(\rb\006proto3"
};
static ::absl::once_flag descriptor_table_GameCharacterService_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_GameCharacterService_2eproto = {
    false,
    false,
    719,
    descriptor_table_protodef_GameCharacterService_2eproto,
    "GameCharacterService.proto",
    &descriptor_table_GameCharacterService_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_default_instances,
    TableStruct_GameCharacterService_2eproto::offsets,
    file_level_metadata_GameCharacterService_2eproto,
    file_level_enum_descriptors_GameCharacterService_2eproto,
    file_level_service_descriptors_GameCharacterService_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_GameCharacterService_2eproto_getter() {
  return &descriptor_table_GameCharacterService_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_GameCharacterService_2eproto(&descriptor_table_GameCharacterService_2eproto);
const ::google::protobuf::EnumDescriptor* GameCharacterServiceRequestWrapper_RequestType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_GameCharacterService_2eproto);
  return file_level_enum_descriptors_GameCharacterService_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t GameCharacterServiceRequestWrapper_RequestType_internal_data_[] = {
    65536u, 0u, };
bool GameCharacterServiceRequestWrapper_RequestType_IsValid(int value) {
  return 0 <= value && value <= 0;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr GameCharacterServiceRequestWrapper_RequestType GameCharacterServiceRequestWrapper::REQUESTPLAYERINITIALDATA;
constexpr GameCharacterServiceRequestWrapper_RequestType GameCharacterServiceRequestWrapper::RequestType_MIN;
constexpr GameCharacterServiceRequestWrapper_RequestType GameCharacterServiceRequestWrapper::RequestType_MAX;
constexpr int GameCharacterServiceRequestWrapper::RequestType_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
const ::google::protobuf::EnumDescriptor* GameCharacterServiceResponseWrapper_ResponseType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_GameCharacterService_2eproto);
  return file_level_enum_descriptors_GameCharacterService_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t GameCharacterServiceResponseWrapper_ResponseType_internal_data_[] = {
    65536u, 0u, };
bool GameCharacterServiceResponseWrapper_ResponseType_IsValid(int value) {
  return 0 <= value && value <= 0;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr GameCharacterServiceResponseWrapper_ResponseType GameCharacterServiceResponseWrapper::RESPONSEPLAYERINITIALDATA;
constexpr GameCharacterServiceResponseWrapper_ResponseType GameCharacterServiceResponseWrapper::ResponseType_MIN;
constexpr GameCharacterServiceResponseWrapper_ResponseType GameCharacterServiceResponseWrapper::ResponseType_MAX;
constexpr int GameCharacterServiceResponseWrapper::ResponseType_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
// ===================================================================

class GameCharacterServiceRequestWrapper::_Internal {
 public:
  static constexpr ::int32_t kOneofCaseOffset =
    PROTOBUF_FIELD_OFFSET(::GameCharacterServiceRequestWrapper, _impl_._oneof_case_);
  static const ::RequestPlayerInitialData& request_player_initial_data(const GameCharacterServiceRequestWrapper* msg);
};

const ::RequestPlayerInitialData& GameCharacterServiceRequestWrapper::_Internal::request_player_initial_data(const GameCharacterServiceRequestWrapper* msg) {
  return *msg->_impl_.request_.request_player_initial_data_;
}
void GameCharacterServiceRequestWrapper::set_allocated_request_player_initial_data(::RequestPlayerInitialData* request_player_initial_data) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_request();
  if (request_player_initial_data) {
    ::google::protobuf::Arena* submessage_arena = request_player_initial_data->GetArena();
    if (message_arena != submessage_arena) {
      request_player_initial_data = ::google::protobuf::internal::GetOwnedMessage(message_arena, request_player_initial_data, submessage_arena);
    }
    set_has_request_player_initial_data();
    _impl_.request_.request_player_initial_data_ = request_player_initial_data;
  }
  // @@protoc_insertion_point(field_set_allocated:GameCharacterServiceRequestWrapper.request_player_initial_data)
}
GameCharacterServiceRequestWrapper::GameCharacterServiceRequestWrapper(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:GameCharacterServiceRequestWrapper)
}
inline PROTOBUF_NDEBUG_INLINE GameCharacterServiceRequestWrapper::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : request_{},
        _cached_size_{0},
        _oneof_case_{from._oneof_case_[0]} {}

GameCharacterServiceRequestWrapper::GameCharacterServiceRequestWrapper(
    ::google::protobuf::Arena* arena,
    const GameCharacterServiceRequestWrapper& from)
    : ::google::protobuf::Message(arena) {
  GameCharacterServiceRequestWrapper* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.request_type_ = from._impl_.request_type_;
  switch (request_case()) {
    case REQUEST_NOT_SET:
      break;
      case kRequestPlayerInitialData:
        _impl_.request_.request_player_initial_data_ = CreateMaybeMessage<::RequestPlayerInitialData>(arena, *from._impl_.request_.request_player_initial_data_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:GameCharacterServiceRequestWrapper)
}
inline PROTOBUF_NDEBUG_INLINE GameCharacterServiceRequestWrapper::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : request_{},
        _cached_size_{0},
        _oneof_case_{} {}

inline void GameCharacterServiceRequestWrapper::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.request_type_ = {};
}
GameCharacterServiceRequestWrapper::~GameCharacterServiceRequestWrapper() {
  // @@protoc_insertion_point(destructor:GameCharacterServiceRequestWrapper)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void GameCharacterServiceRequestWrapper::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  if (has_request()) {
    clear_request();
  }
  _impl_.~Impl_();
}

void GameCharacterServiceRequestWrapper::clear_request() {
// @@protoc_insertion_point(one_of_clear_start:GameCharacterServiceRequestWrapper)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  switch (request_case()) {
    case kRequestPlayerInitialData: {
      if (GetArena() == nullptr) {
        delete _impl_.request_.request_player_initial_data_;
      }
      break;
    }
    case REQUEST_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = REQUEST_NOT_SET;
}


PROTOBUF_NOINLINE void GameCharacterServiceRequestWrapper::Clear() {
// @@protoc_insertion_point(message_clear_start:GameCharacterServiceRequestWrapper)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.request_type_ = 0;
  clear_request();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* GameCharacterServiceRequestWrapper::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 2, 1, 0, 2> GameCharacterServiceRequestWrapper::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_GameCharacterServiceRequestWrapper_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // .GameCharacterServiceRequestWrapper.RequestType request_type = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(GameCharacterServiceRequestWrapper, _impl_.request_type_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(GameCharacterServiceRequestWrapper, _impl_.request_type_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .GameCharacterServiceRequestWrapper.RequestType request_type = 1;
    {PROTOBUF_FIELD_OFFSET(GameCharacterServiceRequestWrapper, _impl_.request_type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // .RequestPlayerInitialData request_player_initial_data = 2;
    {PROTOBUF_FIELD_OFFSET(GameCharacterServiceRequestWrapper, _impl_.request_.request_player_initial_data_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::RequestPlayerInitialData>()},
  }}, {{
  }},
};

::uint8_t* GameCharacterServiceRequestWrapper::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:GameCharacterServiceRequestWrapper)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .GameCharacterServiceRequestWrapper.RequestType request_type = 1;
  if (this->_internal_request_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_request_type(), target);
  }

  // .RequestPlayerInitialData request_player_initial_data = 2;
  if (request_case() == kRequestPlayerInitialData) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, _Internal::request_player_initial_data(this),
        _Internal::request_player_initial_data(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GameCharacterServiceRequestWrapper)
  return target;
}

::size_t GameCharacterServiceRequestWrapper::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:GameCharacterServiceRequestWrapper)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .GameCharacterServiceRequestWrapper.RequestType request_type = 1;
  if (this->_internal_request_type() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_request_type());
  }

  switch (request_case()) {
    // .RequestPlayerInitialData request_player_initial_data = 2;
    case kRequestPlayerInitialData: {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.request_.request_player_initial_data_);
      break;
    }
    case REQUEST_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData GameCharacterServiceRequestWrapper::_class_data_ = {
    GameCharacterServiceRequestWrapper::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* GameCharacterServiceRequestWrapper::GetClassData() const {
  return &_class_data_;
}

void GameCharacterServiceRequestWrapper::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<GameCharacterServiceRequestWrapper*>(&to_msg);
  auto& from = static_cast<const GameCharacterServiceRequestWrapper&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:GameCharacterServiceRequestWrapper)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_request_type() != 0) {
    _this->_internal_set_request_type(from._internal_request_type());
  }
  switch (from.request_case()) {
    case kRequestPlayerInitialData: {
      _this->_internal_mutable_request_player_initial_data()->::RequestPlayerInitialData::MergeFrom(
          from._internal_request_player_initial_data());
      break;
    }
    case REQUEST_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GameCharacterServiceRequestWrapper::CopyFrom(const GameCharacterServiceRequestWrapper& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GameCharacterServiceRequestWrapper)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool GameCharacterServiceRequestWrapper::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* GameCharacterServiceRequestWrapper::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void GameCharacterServiceRequestWrapper::InternalSwap(GameCharacterServiceRequestWrapper* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.request_type_, other->_impl_.request_type_);
  swap(_impl_.request_, other->_impl_.request_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata GameCharacterServiceRequestWrapper::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_GameCharacterService_2eproto_getter, &descriptor_table_GameCharacterService_2eproto_once,
      file_level_metadata_GameCharacterService_2eproto[0]);
}
// ===================================================================

class GameCharacterServiceResponseWrapper::_Internal {
 public:
  static constexpr ::int32_t kOneofCaseOffset =
    PROTOBUF_FIELD_OFFSET(::GameCharacterServiceResponseWrapper, _impl_._oneof_case_);
  static const ::ResponsePlayerInitialData& response_player_initial_data(const GameCharacterServiceResponseWrapper* msg);
};

const ::ResponsePlayerInitialData& GameCharacterServiceResponseWrapper::_Internal::response_player_initial_data(const GameCharacterServiceResponseWrapper* msg) {
  return *msg->_impl_.response_.response_player_initial_data_;
}
void GameCharacterServiceResponseWrapper::set_allocated_response_player_initial_data(::ResponsePlayerInitialData* response_player_initial_data) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_response();
  if (response_player_initial_data) {
    ::google::protobuf::Arena* submessage_arena = response_player_initial_data->GetArena();
    if (message_arena != submessage_arena) {
      response_player_initial_data = ::google::protobuf::internal::GetOwnedMessage(message_arena, response_player_initial_data, submessage_arena);
    }
    set_has_response_player_initial_data();
    _impl_.response_.response_player_initial_data_ = response_player_initial_data;
  }
  // @@protoc_insertion_point(field_set_allocated:GameCharacterServiceResponseWrapper.response_player_initial_data)
}
GameCharacterServiceResponseWrapper::GameCharacterServiceResponseWrapper(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:GameCharacterServiceResponseWrapper)
}
inline PROTOBUF_NDEBUG_INLINE GameCharacterServiceResponseWrapper::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : response_{},
        _cached_size_{0},
        _oneof_case_{from._oneof_case_[0]} {}

GameCharacterServiceResponseWrapper::GameCharacterServiceResponseWrapper(
    ::google::protobuf::Arena* arena,
    const GameCharacterServiceResponseWrapper& from)
    : ::google::protobuf::Message(arena) {
  GameCharacterServiceResponseWrapper* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.response_type_ = from._impl_.response_type_;
  switch (response_case()) {
    case RESPONSE_NOT_SET:
      break;
      case kResponsePlayerInitialData:
        _impl_.response_.response_player_initial_data_ = CreateMaybeMessage<::ResponsePlayerInitialData>(arena, *from._impl_.response_.response_player_initial_data_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:GameCharacterServiceResponseWrapper)
}
inline PROTOBUF_NDEBUG_INLINE GameCharacterServiceResponseWrapper::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : response_{},
        _cached_size_{0},
        _oneof_case_{} {}

inline void GameCharacterServiceResponseWrapper::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.response_type_ = {};
}
GameCharacterServiceResponseWrapper::~GameCharacterServiceResponseWrapper() {
  // @@protoc_insertion_point(destructor:GameCharacterServiceResponseWrapper)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void GameCharacterServiceResponseWrapper::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  if (has_response()) {
    clear_response();
  }
  _impl_.~Impl_();
}

void GameCharacterServiceResponseWrapper::clear_response() {
// @@protoc_insertion_point(one_of_clear_start:GameCharacterServiceResponseWrapper)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  switch (response_case()) {
    case kResponsePlayerInitialData: {
      if (GetArena() == nullptr) {
        delete _impl_.response_.response_player_initial_data_;
      }
      break;
    }
    case RESPONSE_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = RESPONSE_NOT_SET;
}


PROTOBUF_NOINLINE void GameCharacterServiceResponseWrapper::Clear() {
// @@protoc_insertion_point(message_clear_start:GameCharacterServiceResponseWrapper)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.response_type_ = 0;
  clear_response();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* GameCharacterServiceResponseWrapper::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 2, 1, 0, 2> GameCharacterServiceResponseWrapper::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_GameCharacterServiceResponseWrapper_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // .GameCharacterServiceResponseWrapper.ResponseType response_type = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(GameCharacterServiceResponseWrapper, _impl_.response_type_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(GameCharacterServiceResponseWrapper, _impl_.response_type_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .GameCharacterServiceResponseWrapper.ResponseType response_type = 1;
    {PROTOBUF_FIELD_OFFSET(GameCharacterServiceResponseWrapper, _impl_.response_type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // .ResponsePlayerInitialData response_player_initial_data = 2;
    {PROTOBUF_FIELD_OFFSET(GameCharacterServiceResponseWrapper, _impl_.response_.response_player_initial_data_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::ResponsePlayerInitialData>()},
  }}, {{
  }},
};

::uint8_t* GameCharacterServiceResponseWrapper::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:GameCharacterServiceResponseWrapper)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .GameCharacterServiceResponseWrapper.ResponseType response_type = 1;
  if (this->_internal_response_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_response_type(), target);
  }

  // .ResponsePlayerInitialData response_player_initial_data = 2;
  if (response_case() == kResponsePlayerInitialData) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, _Internal::response_player_initial_data(this),
        _Internal::response_player_initial_data(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GameCharacterServiceResponseWrapper)
  return target;
}

::size_t GameCharacterServiceResponseWrapper::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:GameCharacterServiceResponseWrapper)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .GameCharacterServiceResponseWrapper.ResponseType response_type = 1;
  if (this->_internal_response_type() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_response_type());
  }

  switch (response_case()) {
    // .ResponsePlayerInitialData response_player_initial_data = 2;
    case kResponsePlayerInitialData: {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.response_.response_player_initial_data_);
      break;
    }
    case RESPONSE_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData GameCharacterServiceResponseWrapper::_class_data_ = {
    GameCharacterServiceResponseWrapper::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* GameCharacterServiceResponseWrapper::GetClassData() const {
  return &_class_data_;
}

void GameCharacterServiceResponseWrapper::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<GameCharacterServiceResponseWrapper*>(&to_msg);
  auto& from = static_cast<const GameCharacterServiceResponseWrapper&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:GameCharacterServiceResponseWrapper)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_response_type() != 0) {
    _this->_internal_set_response_type(from._internal_response_type());
  }
  switch (from.response_case()) {
    case kResponsePlayerInitialData: {
      _this->_internal_mutable_response_player_initial_data()->::ResponsePlayerInitialData::MergeFrom(
          from._internal_response_player_initial_data());
      break;
    }
    case RESPONSE_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GameCharacterServiceResponseWrapper::CopyFrom(const GameCharacterServiceResponseWrapper& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GameCharacterServiceResponseWrapper)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool GameCharacterServiceResponseWrapper::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* GameCharacterServiceResponseWrapper::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void GameCharacterServiceResponseWrapper::InternalSwap(GameCharacterServiceResponseWrapper* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.response_type_, other->_impl_.response_type_);
  swap(_impl_.response_, other->_impl_.response_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata GameCharacterServiceResponseWrapper::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_GameCharacterService_2eproto_getter, &descriptor_table_GameCharacterService_2eproto_once,
      file_level_metadata_GameCharacterService_2eproto[1]);
}
// ===================================================================

class RequestPlayerInitialData::_Internal {
 public:
};

RequestPlayerInitialData::RequestPlayerInitialData(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:RequestPlayerInitialData)
}
inline PROTOBUF_NDEBUG_INLINE RequestPlayerInitialData::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : player_guid_(arena, from.player_guid_),
        _cached_size_{0} {}

RequestPlayerInitialData::RequestPlayerInitialData(
    ::google::protobuf::Arena* arena,
    const RequestPlayerInitialData& from)
    : ::google::protobuf::Message(arena) {
  RequestPlayerInitialData* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:RequestPlayerInitialData)
}
inline PROTOBUF_NDEBUG_INLINE RequestPlayerInitialData::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : player_guid_(arena),
        _cached_size_{0} {}

inline void RequestPlayerInitialData::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
RequestPlayerInitialData::~RequestPlayerInitialData() {
  // @@protoc_insertion_point(destructor:RequestPlayerInitialData)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void RequestPlayerInitialData::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.player_guid_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void RequestPlayerInitialData::Clear() {
// @@protoc_insertion_point(message_clear_start:RequestPlayerInitialData)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.player_guid_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* RequestPlayerInitialData::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 44, 2> RequestPlayerInitialData::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_RequestPlayerInitialData_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string player_guid = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(RequestPlayerInitialData, _impl_.player_guid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string player_guid = 1;
    {PROTOBUF_FIELD_OFFSET(RequestPlayerInitialData, _impl_.player_guid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\30\13\0\0\0\0\0\0"
    "RequestPlayerInitialData"
    "player_guid"
  }},
};

::uint8_t* RequestPlayerInitialData::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:RequestPlayerInitialData)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string player_guid = 1;
  if (!this->_internal_player_guid().empty()) {
    const std::string& _s = this->_internal_player_guid();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "RequestPlayerInitialData.player_guid");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:RequestPlayerInitialData)
  return target;
}

::size_t RequestPlayerInitialData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:RequestPlayerInitialData)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string player_guid = 1;
  if (!this->_internal_player_guid().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_player_guid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData RequestPlayerInitialData::_class_data_ = {
    RequestPlayerInitialData::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* RequestPlayerInitialData::GetClassData() const {
  return &_class_data_;
}

void RequestPlayerInitialData::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<RequestPlayerInitialData*>(&to_msg);
  auto& from = static_cast<const RequestPlayerInitialData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:RequestPlayerInitialData)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_player_guid().empty()) {
    _this->_internal_set_player_guid(from._internal_player_guid());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RequestPlayerInitialData::CopyFrom(const RequestPlayerInitialData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:RequestPlayerInitialData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool RequestPlayerInitialData::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* RequestPlayerInitialData::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void RequestPlayerInitialData::InternalSwap(RequestPlayerInitialData* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.player_guid_, &other->_impl_.player_guid_, arena);
}

::google::protobuf::Metadata RequestPlayerInitialData::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_GameCharacterService_2eproto_getter, &descriptor_table_GameCharacterService_2eproto_once,
      file_level_metadata_GameCharacterService_2eproto[2]);
}
// ===================================================================

class ResponsePlayerInitialData::_Internal {
 public:
};

ResponsePlayerInitialData::ResponsePlayerInitialData(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ResponsePlayerInitialData)
}
inline PROTOBUF_NDEBUG_INLINE ResponsePlayerInitialData::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : player_name_(arena, from.player_name_),
        _cached_size_{0} {}

ResponsePlayerInitialData::ResponsePlayerInitialData(
    ::google::protobuf::Arena* arena,
    const ResponsePlayerInitialData& from)
    : ::google::protobuf::Message(arena) {
  ResponsePlayerInitialData* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, position_x_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, position_x_),
           offsetof(Impl_, player_movementspeed_) -
               offsetof(Impl_, position_x_) +
               sizeof(Impl_::player_movementspeed_));

  // @@protoc_insertion_point(copy_constructor:ResponsePlayerInitialData)
}
inline PROTOBUF_NDEBUG_INLINE ResponsePlayerInitialData::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : player_name_(arena),
        _cached_size_{0} {}

inline void ResponsePlayerInitialData::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, position_x_),
           0,
           offsetof(Impl_, player_movementspeed_) -
               offsetof(Impl_, position_x_) +
               sizeof(Impl_::player_movementspeed_));
}
ResponsePlayerInitialData::~ResponsePlayerInitialData() {
  // @@protoc_insertion_point(destructor:ResponsePlayerInitialData)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ResponsePlayerInitialData::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.player_name_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void ResponsePlayerInitialData::Clear() {
// @@protoc_insertion_point(message_clear_start:ResponsePlayerInitialData)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.player_name_.ClearToEmpty();
  ::memset(&_impl_.position_x_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.player_movementspeed_) -
      reinterpret_cast<char*>(&_impl_.position_x_)) + sizeof(_impl_.player_movementspeed_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ResponsePlayerInitialData::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 0, 45, 2> ResponsePlayerInitialData::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_ResponsePlayerInitialData_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string player_name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ResponsePlayerInitialData, _impl_.player_name_)}},
    // float position_x = 2;
    {::_pbi::TcParser::FastF32S1,
     {21, 63, 0, PROTOBUF_FIELD_OFFSET(ResponsePlayerInitialData, _impl_.position_x_)}},
    // float position_y = 3;
    {::_pbi::TcParser::FastF32S1,
     {29, 63, 0, PROTOBUF_FIELD_OFFSET(ResponsePlayerInitialData, _impl_.position_y_)}},
    // float position_z = 4;
    {::_pbi::TcParser::FastF32S1,
     {37, 63, 0, PROTOBUF_FIELD_OFFSET(ResponsePlayerInitialData, _impl_.position_z_)}},
    // uint32 rotation_y = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ResponsePlayerInitialData, _impl_.rotation_y_), 63>(),
     {40, 63, 0, PROTOBUF_FIELD_OFFSET(ResponsePlayerInitialData, _impl_.rotation_y_)}},
    // uint32 player_movementspeed = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ResponsePlayerInitialData, _impl_.player_movementspeed_), 63>(),
     {48, 63, 0, PROTOBUF_FIELD_OFFSET(ResponsePlayerInitialData, _impl_.player_movementspeed_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string player_name = 1;
    {PROTOBUF_FIELD_OFFSET(ResponsePlayerInitialData, _impl_.player_name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // float position_x = 2;
    {PROTOBUF_FIELD_OFFSET(ResponsePlayerInitialData, _impl_.position_x_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // float position_y = 3;
    {PROTOBUF_FIELD_OFFSET(ResponsePlayerInitialData, _impl_.position_y_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // float position_z = 4;
    {PROTOBUF_FIELD_OFFSET(ResponsePlayerInitialData, _impl_.position_z_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // uint32 rotation_y = 5;
    {PROTOBUF_FIELD_OFFSET(ResponsePlayerInitialData, _impl_.rotation_y_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 player_movementspeed = 6;
    {PROTOBUF_FIELD_OFFSET(ResponsePlayerInitialData, _impl_.player_movementspeed_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
    "\31\13\0\0\0\0\0\0"
    "ResponsePlayerInitialData"
    "player_name"
  }},
};

::uint8_t* ResponsePlayerInitialData::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ResponsePlayerInitialData)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string player_name = 1;
  if (!this->_internal_player_name().empty()) {
    const std::string& _s = this->_internal_player_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ResponsePlayerInitialData.player_name");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // float position_x = 2;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_position_x = this->_internal_position_x();
  ::uint32_t raw_position_x;
  memcpy(&raw_position_x, &tmp_position_x, sizeof(tmp_position_x));
  if (raw_position_x != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        2, this->_internal_position_x(), target);
  }

  // float position_y = 3;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_position_y = this->_internal_position_y();
  ::uint32_t raw_position_y;
  memcpy(&raw_position_y, &tmp_position_y, sizeof(tmp_position_y));
  if (raw_position_y != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        3, this->_internal_position_y(), target);
  }

  // float position_z = 4;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_position_z = this->_internal_position_z();
  ::uint32_t raw_position_z;
  memcpy(&raw_position_z, &tmp_position_z, sizeof(tmp_position_z));
  if (raw_position_z != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        4, this->_internal_position_z(), target);
  }

  // uint32 rotation_y = 5;
  if (this->_internal_rotation_y() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        5, this->_internal_rotation_y(), target);
  }

  // uint32 player_movementspeed = 6;
  if (this->_internal_player_movementspeed() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        6, this->_internal_player_movementspeed(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ResponsePlayerInitialData)
  return target;
}

::size_t ResponsePlayerInitialData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ResponsePlayerInitialData)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string player_name = 1;
  if (!this->_internal_player_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_player_name());
  }

  // float position_x = 2;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_position_x = this->_internal_position_x();
  ::uint32_t raw_position_x;
  memcpy(&raw_position_x, &tmp_position_x, sizeof(tmp_position_x));
  if (raw_position_x != 0) {
    total_size += 5;
  }

  // float position_y = 3;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_position_y = this->_internal_position_y();
  ::uint32_t raw_position_y;
  memcpy(&raw_position_y, &tmp_position_y, sizeof(tmp_position_y));
  if (raw_position_y != 0) {
    total_size += 5;
  }

  // float position_z = 4;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_position_z = this->_internal_position_z();
  ::uint32_t raw_position_z;
  memcpy(&raw_position_z, &tmp_position_z, sizeof(tmp_position_z));
  if (raw_position_z != 0) {
    total_size += 5;
  }

  // uint32 rotation_y = 5;
  if (this->_internal_rotation_y() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_rotation_y());
  }

  // uint32 player_movementspeed = 6;
  if (this->_internal_player_movementspeed() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_player_movementspeed());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData ResponsePlayerInitialData::_class_data_ = {
    ResponsePlayerInitialData::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* ResponsePlayerInitialData::GetClassData() const {
  return &_class_data_;
}

void ResponsePlayerInitialData::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<ResponsePlayerInitialData*>(&to_msg);
  auto& from = static_cast<const ResponsePlayerInitialData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ResponsePlayerInitialData)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_player_name().empty()) {
    _this->_internal_set_player_name(from._internal_player_name());
  }
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_position_x = from._internal_position_x();
  ::uint32_t raw_position_x;
  memcpy(&raw_position_x, &tmp_position_x, sizeof(tmp_position_x));
  if (raw_position_x != 0) {
    _this->_internal_set_position_x(from._internal_position_x());
  }
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_position_y = from._internal_position_y();
  ::uint32_t raw_position_y;
  memcpy(&raw_position_y, &tmp_position_y, sizeof(tmp_position_y));
  if (raw_position_y != 0) {
    _this->_internal_set_position_y(from._internal_position_y());
  }
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_position_z = from._internal_position_z();
  ::uint32_t raw_position_z;
  memcpy(&raw_position_z, &tmp_position_z, sizeof(tmp_position_z));
  if (raw_position_z != 0) {
    _this->_internal_set_position_z(from._internal_position_z());
  }
  if (from._internal_rotation_y() != 0) {
    _this->_internal_set_rotation_y(from._internal_rotation_y());
  }
  if (from._internal_player_movementspeed() != 0) {
    _this->_internal_set_player_movementspeed(from._internal_player_movementspeed());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ResponsePlayerInitialData::CopyFrom(const ResponsePlayerInitialData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ResponsePlayerInitialData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ResponsePlayerInitialData::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* ResponsePlayerInitialData::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void ResponsePlayerInitialData::InternalSwap(ResponsePlayerInitialData* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.player_name_, &other->_impl_.player_name_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ResponsePlayerInitialData, _impl_.player_movementspeed_)
      + sizeof(ResponsePlayerInitialData::_impl_.player_movementspeed_)
      - PROTOBUF_FIELD_OFFSET(ResponsePlayerInitialData, _impl_.position_x_)>(
          reinterpret_cast<char*>(&_impl_.position_x_),
          reinterpret_cast<char*>(&other->_impl_.position_x_));
}

::google::protobuf::Metadata ResponsePlayerInitialData::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_GameCharacterService_2eproto_getter, &descriptor_table_GameCharacterService_2eproto_once,
      file_level_metadata_GameCharacterService_2eproto[3]);
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
