// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: DatabaseProtocol.proto
#ifndef GRPC_DatabaseProtocol_2eproto__INCLUDED
#define GRPC_DatabaseProtocol_2eproto__INCLUDED

#include "DatabaseProtocol.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace database {

class PlayerService final {
 public:
  static constexpr char const* service_full_name() {
    return "database.PlayerService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetPlayerInitialData(::grpc::ClientContext* context, const ::database::RequestPlayerInitialData& request, ::database::ResponsePlayerInitialData* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::database::ResponsePlayerInitialData>> AsyncGetPlayerInitialData(::grpc::ClientContext* context, const ::database::RequestPlayerInitialData& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::database::ResponsePlayerInitialData>>(AsyncGetPlayerInitialDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::database::ResponsePlayerInitialData>> PrepareAsyncGetPlayerInitialData(::grpc::ClientContext* context, const ::database::RequestPlayerInitialData& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::database::ResponsePlayerInitialData>>(PrepareAsyncGetPlayerInitialDataRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetPlayerInitialData(::grpc::ClientContext* context, const ::database::RequestPlayerInitialData* request, ::database::ResponsePlayerInitialData* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetPlayerInitialData(::grpc::ClientContext* context, const ::database::RequestPlayerInitialData* request, ::database::ResponsePlayerInitialData* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::database::ResponsePlayerInitialData>* AsyncGetPlayerInitialDataRaw(::grpc::ClientContext* context, const ::database::RequestPlayerInitialData& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::database::ResponsePlayerInitialData>* PrepareAsyncGetPlayerInitialDataRaw(::grpc::ClientContext* context, const ::database::RequestPlayerInitialData& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetPlayerInitialData(::grpc::ClientContext* context, const ::database::RequestPlayerInitialData& request, ::database::ResponsePlayerInitialData* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::database::ResponsePlayerInitialData>> AsyncGetPlayerInitialData(::grpc::ClientContext* context, const ::database::RequestPlayerInitialData& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::database::ResponsePlayerInitialData>>(AsyncGetPlayerInitialDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::database::ResponsePlayerInitialData>> PrepareAsyncGetPlayerInitialData(::grpc::ClientContext* context, const ::database::RequestPlayerInitialData& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::database::ResponsePlayerInitialData>>(PrepareAsyncGetPlayerInitialDataRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetPlayerInitialData(::grpc::ClientContext* context, const ::database::RequestPlayerInitialData* request, ::database::ResponsePlayerInitialData* response, std::function<void(::grpc::Status)>) override;
      void GetPlayerInitialData(::grpc::ClientContext* context, const ::database::RequestPlayerInitialData* request, ::database::ResponsePlayerInitialData* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::database::ResponsePlayerInitialData>* AsyncGetPlayerInitialDataRaw(::grpc::ClientContext* context, const ::database::RequestPlayerInitialData& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::database::ResponsePlayerInitialData>* PrepareAsyncGetPlayerInitialDataRaw(::grpc::ClientContext* context, const ::database::RequestPlayerInitialData& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetPlayerInitialData_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetPlayerInitialData(::grpc::ServerContext* context, const ::database::RequestPlayerInitialData* request, ::database::ResponsePlayerInitialData* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetPlayerInitialData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetPlayerInitialData() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetPlayerInitialData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPlayerInitialData(::grpc::ServerContext* /*context*/, const ::database::RequestPlayerInitialData* /*request*/, ::database::ResponsePlayerInitialData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetPlayerInitialData(::grpc::ServerContext* context, ::database::RequestPlayerInitialData* request, ::grpc::ServerAsyncResponseWriter< ::database::ResponsePlayerInitialData>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetPlayerInitialData<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetPlayerInitialData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetPlayerInitialData() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::database::RequestPlayerInitialData, ::database::ResponsePlayerInitialData>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::database::RequestPlayerInitialData* request, ::database::ResponsePlayerInitialData* response) { return this->GetPlayerInitialData(context, request, response); }));}
    void SetMessageAllocatorFor_GetPlayerInitialData(
        ::grpc::MessageAllocator< ::database::RequestPlayerInitialData, ::database::ResponsePlayerInitialData>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::database::RequestPlayerInitialData, ::database::ResponsePlayerInitialData>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetPlayerInitialData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPlayerInitialData(::grpc::ServerContext* /*context*/, const ::database::RequestPlayerInitialData* /*request*/, ::database::ResponsePlayerInitialData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetPlayerInitialData(
      ::grpc::CallbackServerContext* /*context*/, const ::database::RequestPlayerInitialData* /*request*/, ::database::ResponsePlayerInitialData* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetPlayerInitialData<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetPlayerInitialData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetPlayerInitialData() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetPlayerInitialData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPlayerInitialData(::grpc::ServerContext* /*context*/, const ::database::RequestPlayerInitialData* /*request*/, ::database::ResponsePlayerInitialData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetPlayerInitialData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetPlayerInitialData() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetPlayerInitialData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPlayerInitialData(::grpc::ServerContext* /*context*/, const ::database::RequestPlayerInitialData* /*request*/, ::database::ResponsePlayerInitialData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetPlayerInitialData(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetPlayerInitialData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetPlayerInitialData() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetPlayerInitialData(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetPlayerInitialData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPlayerInitialData(::grpc::ServerContext* /*context*/, const ::database::RequestPlayerInitialData* /*request*/, ::database::ResponsePlayerInitialData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetPlayerInitialData(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetPlayerInitialData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetPlayerInitialData() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::database::RequestPlayerInitialData, ::database::ResponsePlayerInitialData>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::database::RequestPlayerInitialData, ::database::ResponsePlayerInitialData>* streamer) {
                       return this->StreamedGetPlayerInitialData(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetPlayerInitialData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetPlayerInitialData(::grpc::ServerContext* /*context*/, const ::database::RequestPlayerInitialData* /*request*/, ::database::ResponsePlayerInitialData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetPlayerInitialData(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::database::RequestPlayerInitialData,::database::ResponsePlayerInitialData>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetPlayerInitialData<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetPlayerInitialData<Service > StreamedService;
};

}  // namespace database


#endif  // GRPC_DatabaseProtocol_2eproto__INCLUDED
